apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/shantdashjianeducation/order-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/shantdashjianeducation/order-service
  newTag: d9fef01ffb73d9deb4bfaa7b8c7c172cc48216a3

replicas:
- count: 1
  name: order-service
